name: fababean_env
channels:
  - defaults
  - conda-forge

dependencies:
  - pip
  - numpy==1.26.0
  - pandas
  - matplotlib
  - seaborn
  - git
  - pip:
      - scikit-learn
      - opencv-python
      - scikit-image
      - circle-fit
      - openpyxl
      - torch
      - torchvision
      - torchaudio --index-url https://download.pytorch.org/whl/cu118
